iDs = 	{
			'luft' : '0',
			'stein': '1',
			'gras' : '2',
			'erde': '3',
			'fels' : '4',
			'holz': '5',
			'eiche' : '6',
			'felsstein': '7',
			'fluessiges_Wasser' : '8',
			'ruhiges_Wasser': '9',
			'fliessende_Lava' : '10',
			'ruhige_Lava': '11',
			'sand' : '12',
			'schotter': '13',
			'golderz' : '14',
			'eisenerz': '15',
			'kohleerz' : '16',
			'baumstamm': '17',
			'blaetter' : '18',
			'schwamm': '19',
			'glas' : '20',
			'lapis_lazuli_erz': '21',
			'lapis_lazuli' : '22',
			'dispenser': '23',
			'sandstein' : '24',
			'noteblock': '25',
			'bett' : '26',
			'powerd_rail': '27',
			'detector_rail' : '28',
			'sticky_piston': '29',
			'spinnweben' : '30',
			'totes_gestrueb': '31',
			'toter_busch' : '32',
			'piston': '33',
			'piston_head' : '34',
			'wolle': '35',
			'gelbe_blume' : '37',
			'rote_blume': '38',
			'brauner_pilz' : '39',
			'roter_pilz': '40',
			'gold' : '41',
			'eisen': '42',
			'doppelstein' : '43',
			'steinplattte': '44',
			'ziegelsteine' : '45',
			'tnt': '46',
			'buecherregal' : '47',
			'moosstein': '48',
			'obsidian' : '49',
			'fackel': '50',
			'feuer' : '51',
			'monster' : '52',
			'holzstufen' : '53',
			'truhe' : '54',
			'redstone' : '55',
			'diamanten_erz' : '56',
			'diamant' : '57',
			'tisch' : '58',
			'weizen' : '59',
			'acker' : '60',
			'kamin' : '61',
			'brennender_kamin' : '62',
			'schild' : '63',
			'tuer' : '64',
			'leiter' : '65',
			'schiene' : '66',
			'steintreppe' : '67',
			'bergschild' : '68',
			'hebel' : '69',
			'stein_druckplatte' : '70',
			'eisentuer' : '71',
			'holz_druckplatte' : '72',
			'redstone_erz' : '73',
			'gluehendes_redstone_erz' : '74',
			'redstone_fackel' : '75',
			'redstone_fackel_brennend' : '76',
			'steinknopf' : '77',
			'schnee' : '78',
			'eis' : '79',
			'schneeblock' : '80'
		}

iDDs = 	{
			'0' : 'luft',
			'1' : 'stein',
			'2' : 'gras',
			'3' : 'erde',
			'4' : 'fels',
			'5' : 'holz',
			'6' : 'eiche',
			'7' : 'felsstein',
			'8' : 'fluessiges_Wasser',
			'9' : 'ruhiges_Wasser',
			'10' : 'fliessende_Lava',
			'11' : 'ruhige_Lava',
			'12' : 'sand',
			'13' : 'schotter',
			'14' : 'golderz',
			'15' : 'eisenerz',
			'16' : 'kohleerz',
			'17' : 'baumstamm',
			'18' : 'blaetter',
			'19' : 'schwamm',
			'20' : 'glas',
			'21' : 'lapis_lazuli_erz',
			'22' : 'lapis_lazuli',
			'23' : 'dispenser',
			'24' : 'sandstein',
			'25' : 'noteblock',
			'26' : 'bett',
			'27' : 'powerd_rail',
			'28' : 'detector_rail',
			'29' : 'sticky_piston',
			'30' : 'spinnweben',
			'31' : 'totes_gestrueb',
			'32' : 'toter_busch',
			'33' : 'piston',
			'34' : 'piston_head',
			'35' : 'wolle',
			'37' : 'gelbe_blume',
			'38' : 'rote_blume',
			'39' : 'brauner_pilz',
			'40' : 'roter_pilz',
			'41' : 'gold',
			'42' : 'eisen',
			'43' : 'doppelstein',
			'44' : 'steinplattte',
			'45' : 'ziegelsteine',
			'46' : 'tnt',
			'47' : 'buecherregal',
			'48' : 'moosstein',
			'49' : 'obsidian',
			'50' : 'fackel',
			'51' : 'feuer',
			'52' : 'monster',
			'53' : 'holzstufen',
			'54' : 'truhe',
			'55' : 'redstone',
			'56' : 'diamanten_erz',
			'57' : 'diamant',
			'58' : 'tisch',
			'59' : 'weizen',
			'60' : 'acker',
			'61' : 'kamin',
			'62' : 'brennender_kamin',
			'63' : 'schild',
			'64' : 'tuer',
			'65' : 'leiter',
			'66' : 'schiene',
			'67' : 'steintreppe',
			'68' : 'bergschild',
			'69' : 'hebel',
			'70' : 'stein_druckplatte',
			'71' : 'eisentuer',
			'72' : 'holz_druckplatte',
			'73' : 'redstone_erz',
			'74' : 'gluehendes_redstone_erz',
			'75' : 'redstone_fackel',
			'76' : 'redstone_fackel_brennend',
			'77' : 'steinknopf',
			'78' : 'schnee',
			'79' : 'eis',
			'80' : 'schneeblock'
		}
